name: Update News and Rebuild Site

on:
  schedule:
    # Runs every 6 hours at minute 0
    - cron: '0 */6 * * *'
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  update-and-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run scraper to fetch new articles
        run: |
          echo "Running scraper to fetch latest AI news..."
          python3 -m scraper.scraper
      
      - name: Build static site
        run: |
          echo "Building static site..."
          python3 build_static.py
      
      - name: Check for changes
        id: check_changes
        run: |
          git diff --quiet data/ia_news.json || echo "changes=true" >> $GITHUB_OUTPUT
      
      - name: Commit and push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/ia_news.json docs/
          git commit -m "🤖 Auto-update: Fetch latest AI news and rebuild site"
          git push
      
      - name: No changes detected
        if: steps.check_changes.outputs.changes != 'true'
        run: |
          echo "No new articles found. Site is up to date."